"A 3D Column Chart"
#Autogenerated by ReportLab guiedit do not edit
from rlextra.graphics.quickchart import QuickChart
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin

class ColumChart(_DrawingEditorMixin,Drawing):
	"""
	3d Column Chart - with 3 series with grid lines
	"""
	def __init__(self,width=400,height=200,*args,**kw):
		Drawing.__init__(self,width,height,*args,**kw)
		self._add(self,QuickChart(),name='chart',validate=None,desc=None)
		self.chart.height               = 200
		self.chart.seriesNames          ='a','b','c'
		self.chart.seriesRelation       = None#
		self.chart.dataLabelsFontSize   = 12
		self.chart.chartSeparation      = 1
		self.chart.data                 = [[100, 120, 140], [110, 130, 150],[200,100,100]]
		self.chart.titleText            = 'Column Chart'
		self.chart.xTitleText           = ''
		self.chart.categoryNames        = ('2009','2010','2012')
		self.chart.chartType='column3d'
		self.transform   = (1, 0, 0, 1, 0, 0)
		self.chart.xAxisGridLines       = 1
		self.chart.yAxisGridLines       = 1

if __name__=="__main__": #NORUNTESTS
	ColumChart().save(formats=['pdf'],outDir='.',fnRoot=None)