# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
    ]
