# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20160406_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NroCamaA', models.CharField(max_length=3)),
                ('FechaA', models.DateField()),
                ('TiempoA', models.DateTimeField()),
                ('DescripcionA', models.TextField()),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_S', models.CharField(max_length=10)),
                ('NombreS', models.CharField(max_length=30)),
                ('ApellidoS', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreU', models.CharField(max_length=30)),
                ('ApellidoU', models.CharField(max_length=30)),
                ('NickU', models.CharField(max_length=30)),
                ('ContraU', models.CharField(max_length=30)),
                ('CorreoU', models.EmailField(max_length=30)),
                ('PistaU', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Atention',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='personal',
            name='Cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Puesto'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='ID_P',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Personal'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='Nombre_U',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuarios'),
        ),
    ]
