# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20160410_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='FechaA',
        ),
    ]
