# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20160425_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='DescripcionA',
            field=models.TextField(default=None),
        ),
    ]
