# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_atencion_nroediciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Area', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_Cama', models.CharField(max_length=3)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_P', models.CharField(max_length=50)),
                ('Apellido_P', models.CharField(max_length=50)),
                ('Fecha_Ingreso', models.DateField()),
                ('Fecha_Salida', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='Nombre_U',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='NroCamaA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cama'),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='cama',
            name='Id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Paciente'),
        ),
    ]
