# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0014_remove_edicion_idusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicion',
            name='IdUsuarios',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='TotalE',
            field=models.IntegerField(),
        ),
    ]
