# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20160523_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicion',
            name='IdUsuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
