# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20160523_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='NroEdicionesA',
            new_name='NroEdiciones',
        ),
    ]
