# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20160523_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edicion',
            name='TotalE',
        ),
        migrations.AddField(
            model_name='edicion',
            name='TiempoE',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
