# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20160523_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicion',
            name='TiempoE',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
