# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20160523_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edicion',
            name='TiempoE',
        ),
        migrations.AddField(
            model_name='edicion',
            name='TotalE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
