# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0024_auto_20160523_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiempoE', models.DateTimeField()),
                ('TotalE', models.IntegerField(default=0)),
                ('IdUsuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='NroEdiciones',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Edicion'),
            preserve_default=False,
        ),
    ]
