# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0027_auto_20160602_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='NroEdiciones',
            new_name='Ediciones',
        ),
        migrations.RemoveField(
            model_name='edicion',
            name='IdUsuarios',
        ),
        migrations.AddField(
            model_name='edicion',
            name='IdUsuarios',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
