# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_auto_20160603_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='Ediciones',
        ),
        migrations.AddField(
            model_name='edicion',
            name='idAtencion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Atencion'),
            preserve_default=False,
        ),
    ]
