# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0030_auto_20160622_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='AlertaMensajeA',
            field=models.CharField(default='Necesito Atencion urgente!', max_length=50),
        ),
    ]
