# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_auto_20160715_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Dni_P',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
