# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0034_auto_20160715_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Dni_P',
            field=models.IntegerField(default=0),
        ),
    ]
