# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_auto_20160715_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cama',
            name='ActivaC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cama',
            name='EstadoC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='ActivoS',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cama',
            name='Area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Area'),
        ),
    ]
