# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_auto_20160717_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Activo_P',
            field=models.BooleanField(default=True),
        ),
    ]
