# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0038_paciente_activo_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='Id_paciente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Paciente'),
        ),
    ]
